Importando pandas e biblotecas

In [34]:
import pandas as pd
df = pd.read_csv('../data/asteroids_data.csv', sep=',')
pd.set_option('display.max_columns', None)
df.head()

,id,neo_id,name,short_name,designation,nasa_url,magnitude,potentially_hazardous,close_approach_data,sentry,api_url,diameter_min_m,diameter_max_m,orbit_id,orbit_determination_date,first_observation_date,last_observation_date,data_arc_days,observations_used,orbit_uncertainty,min_orbit_intersection,jupiter_tisserand,epoch,eccentricity,semi_major_axis,inclination,ascending_node_longitude,orbital_period,perihelion_distance,perihelion_argument,aphelion_distance,perihelion_time,mean_anomaly,mean_motion,equinox,orbit_class_type,orbit_class_desc,orbit_class_range,sentry_data
0,2001620,2001620,1620 Geographos (1951 RA),Geographos,1620,https://ssd.jpl.nasa.gov/tools/sbdb_lookup.htm...,15.26,True,"[{'close_approach_date': '1901-08-23', 'close_...",False,http://api.nasa.gov/neo/rest/v1/neo/2001620?ap...,2358.060680,5272.783976,882,2026-04-19 06:20:43,1951-09-14,2026-04-16,27243,9183,0,0.029359,5.074,2461000.5,0.335512,1.245777,13.335793,337.140792,507.877358,0.827804,277.018390,1.663750,2.461208e+06,212.920449,0.708833,J2000,APO,Near-Earth asteroid orbits which cross the Ear...,a (semi-major axis) > 1.0 AU; q (perihelion) <...,NaN
1,2001863,2001863,1863 Antinous (1948 EA),Antinous,1863,https://ssd.jpl.nasa.gov/tools/sbdb_lookup.htm...,15.35,False,"[{'close_approach_date': '1907-10-11', 'close_...",False,http://api.nasa.gov/neo/rest/v1/neo/2001863?ap...,2262.324906,5058.712276,305,2026-04-18 06:19:45,1948-03-05,2026-04-17,28532,1804,0,0.187310,3.297,2461000.5,0.606266,2.260116,18.378651,345.551216,1241.064828,0.889883,269.074546,3.630348,2.461243e+06,289.564484,0.290073,J2000,APO,Near-Earth asteroid orbits which cross the Ear...,a (semi-major axis) > 1.0 AU; q (perihelion) <...,NaN
2,2001915,2001915,1915 Quetzalcoatl (1953 EA),Quetzalcoatl,1915,https://ssd.jpl.nasa.gov/tools/sbdb_lookup.htm...,18.38,False,"[{'close_approach_date': '1906-03-06', 'close_...",False,http://api.nasa.gov/neo/rest/v1/neo/2001915?ap...,560.473362,1253.256538,13,2024-03-01 04:49:33,1953-03-09,2020-10-25,24702,55,0,0.108832,3.122,2461000.5,0.570225,2.544841,20.399239,162.921649,1482.823498,1.093710,347.755255,3.995972,2.460911e+06,21.616448,0.242780,J2000,AMO,Near-Earth asteroid orbits similar to that of ...,1.017 AU < q (perihelion) < 1.3 AU,NaN
3,2001917,2001917,1917 Cuyo (1968 AA),Cuyo,1917,https://ssd.jpl.nasa.gov/tools/sbdb_lookup.htm...,14.38,False,"[{'close_approach_date': '1926-09-28', 'close_...",False,http://api.nasa.gov/neo/rest/v1/neo/2001917?ap...,3536.347843,7907.514169,654,2026-04-20 06:20:45,1954-05-06,2026-04-19,26281,4164,0,0.071704,3.435,2461000.5,0.505538,2.149051,23.958779,188.274896,1150.717204,1.062625,194.552572,3.235478,2.460489e+06,160.089498,0.312848,J2000,AMO,Near-Earth asteroid orbits similar to that of ...,1.017 AU < q (perihelion) < 1.3 AU,NaN
4,2002063,2002063,2063 Bacchus (1977 HB),Bacchus,2063,https://ssd.jpl.nasa.gov/tools/sbdb_lookup.htm...,17.21,False,"[{'close_approach_date': '1903-03-06', 'close_...",False,http://api.nasa.gov/neo/rest/v1/neo/2002063?ap...,960.627415,2148.028201,258,2025-06-30 20:40:59,1977-04-24,2025-06-15,17584,1561,0,0.066744,5.668,2461000.5,0.349429,1.077999,9.434707,33.036303,408.813985,0.701315,55.350732,1.454683,2.461143e+06,234.787011,0.880596,J2000,APO,Near-Earth asteroid orbits which cross the Ear...,a (semi-major axis) > 1.0 AU; q (perihelion) <...,NaN

**Normalizando colunas e Tratando Nulls**

In [35]:
#Convertendo colunas strings em datetime
colunas = ['orbit_determination_date', 'first_observation_date', 'last_observation_date']
df[colunas] = df[colunas].apply(pd.to_datetime)

In [36]:
#Dropar coluna sentry_data
df = df.drop('sentry_data', axis=1)

#Preenchendo nulls da coluna short_name
def fill_short(df):
    for idx, row in df.iterrows():
        if row['short_name'] == '' or pd.isna(row['short_name']):
            parts = row['name'].split(' ')
            if len(parts) >= 3:
                fill = parts[2][:-1]
                df.at[idx, 'short_name'] = fill
    return df

df = fill_short(df)

#Criando diâmetro médio
df['diameter_medium'] = (df['diameter_max_m'] + df['diameter_min_m']) / 2

df.to_csv('../data/clean_asteroids_data.csv', index=False, sep=',')
df

,id,neo_id,name,short_name,designation,nasa_url,magnitude,potentially_hazardous,close_approach_data,sentry,api_url,diameter_min_m,diameter_max_m,orbit_id,orbit_determination_date,first_observation_date,last_observation_date,data_arc_days,observations_used,orbit_uncertainty,min_orbit_intersection,jupiter_tisserand,epoch,eccentricity,semi_major_axis,inclination,ascending_node_longitude,orbital_period,perihelion_distance,perihelion_argument,aphelion_distance,perihelion_time,mean_anomaly,mean_motion,equinox,orbit_class_type,orbit_class_desc,orbit_class_range,diameter_medium
0,2001620,2001620,1620 Geographos (1951 RA),Geographos,1620,https://ssd.jpl.nasa.gov/tools/sbdb_lookup.htm...,15.26,True,"[{'close_approach_date': '1901-08-23', 'close_...",False,http://api.nasa.gov/neo/rest/v1/neo/2001620?ap...,2358.060680,5272.783976,882,2026-04-19 06:20:43,1951-09-14,2026-04-16,27243,9183,0,0.029359,5.074,2461000.5,0.335512,1.245777,13.335793,337.140792,507.877358,0.827804,277.018390,1.663750,2.461208e+06,212.920449,0.708833,J2000,APO,Near-Earth asteroid orbits which cross the Ear...,a (semi-major axis) > 1.0 AU; q (perihelion) <...,3815.422328
1,2001863,2001863,1863 Antinous (1948 EA),Antinous,1863,https://ssd.jpl.nasa.gov/tools/sbdb_lookup.htm...,15.35,False,"[{'close_approach_date': '1907-10-11', 'close_...",False,http://api.nasa.gov/neo/rest/v1/neo/2001863?ap...,2262.324906,5058.712276,305,2026-04-18 06:19:45,1948-03-05,2026-04-17,28532,1804,0,0.187310,3.297,2461000.5,0.606266,2.260116,18.378651,345.551216,1241.064828,0.889883,269.074546,3.630348,2.461243e+06,289.564484,0.290073,J2000,APO,Near-Earth asteroid orbits which cross the Ear...,a (semi-major axis) > 1.0 AU; q (perihelion) <...,3660.518591
2,2001915,2001915,1915 Quetzalcoatl (1953 EA),Quetzalcoatl,1915,https://ssd.jpl.nasa.gov/tools/sbdb_lookup.htm...,18.38,False,"[{'close_approach_date': '1906-03-06', 'close_...",False,http://api.nasa.gov/neo/rest/v1/neo/2001915?ap...,560.473362,1253.256538,13,2024-03-01 04:49:33,1953-03-09,2020-10-25,24702,55,0,0.108832,3.122,2461000.5,0.570225,2.544841,20.399239,162.921649,1482.823498,1.093710,347.755255,3.995972,2.460911e+06,21.616448,0.242780,J2000,AMO,Near-Earth asteroid orbits similar to that of ...,1.017 AU < q (perihelion) < 1.3 AU,906.864950
3,2001917,2001917,1917 Cuyo (1968 AA),Cuyo,1917,https://ssd.jpl.nasa.gov/tools/sbdb_lookup.htm...,14.38,False,"[{'close_approach_date': '1926-09-28', 'close_...",False,http://api.nasa.gov/neo/rest/v1/neo/2001917?ap...,3536.347843,7907.514169,654,2026-04-20 06:20:45,1954-05-06,2026-04-19,26281,4164,0,0.071704,3.435,2461000.5,0.505538,2.149051,23.958779,188.274896,1150.717204,1.062625,194.552572,3.235478,2.460489e+06,160.089498,0.312848,J2000,AMO,Near-Earth asteroid orbits similar to that of ...,1.017 AU < q (perihelion) < 1.3 AU,5721.931006
4,2002063,2002063,2063 Bacchus (1977 HB),Bacchus,2063,https://ssd.jpl.nasa.gov/tools/sbdb_lookup.htm...,17.21,False,"[{'close_approach_date': '1903-03-06', 'close_...",False,http://api.nasa.gov/neo/rest/v1/neo/2002063?ap...,960.627415,2148.028201,258,2025-06-30 20:40:59,1977-04-24,2025-06-15,17584,1561,0,0.066744,5.668,2461000.5,0.349429,1.077999,9.434707,33.036303,408.813985,0.701315,55.350732,1.454683,2.461143e+06,234.787011,0.880596,J2000,APO,Near-Earth asteroid orbits which cross the Ear...,a (semi-major axis) > 1.0 AU; q (perihelion) <...,1554.327808
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1995,2447221,2447221,447221 (2005 UO5),UO5,447221,https://ssd.jpl.nasa.gov/tools/sbdb_lookup.htm...,20.82,False,[],False,http://api.nasa.gov/neo/rest/v1/neo/2447221?ap...,182.202771,407.417781,51,2025-12-15 05:26:05,2005-10-27,2025-12-15,7354,164,0,0.098846,5.361,2461000.5,0.150343,1.161173,19.679495,50.732906,457.028999,0.986598,76.363267,1.335747,2.461083e+06,294.930387,0.787696,J2000,APO,Near-Earth asteroid orbits which cross the Ear...,a (semi-major axis) > 1.0 AU; q (perihelion) <...,294.810276
1996,2447903,2447903,447903 (2007 XJ20),XJ20,447903,https://ssd.jpl.nasa.gov/tools/sbdb_lookup.htm...,18.58,False,"[{'close_approach_date': '1900-05-13', 'close_...",False,http://api.nasa.gov/neo/rest/v1/neo/2447903?ap...,511.157782,1142.983547,54,2023-03-01 06:47:35,2005-10-28,2022-10-31,6212,177,0,0.150282,3.970,2461000.5,0.599674,1.693178,10.648253,56.541350,804.733647,0.677824,152.013788,2.708531,2.461028e+06,347.824186,0.447353,J2000,APO,Near-Earth asteroid orbits which cross the Ear...,a (semi-major axis) > 1.0 AU; q (perihelion) <...,827.070664
1997,2448003,2448003,448003 (2008 DE),DE,448003,https://ssd.jpl.nasa.gov/tools/sbdb_lookup.htm...,19.58,True,"[{'close_approach_date': '1902-05-26', 'close_...",False,http://api.nasa.gov/neo/rest/v1/neo/2448003?ap...,322.518756,721.173863,90,2026-04-20 06:21:43,2008-02-12,2026-04-19,6641,452,0,0.007019,4.046,2461000.5,0.413388,1.714602,14.756050,55.898623,820.056033,1.005806,179.246318,2.423399,2.461161e+06,289.545183,0.438994,J2000,APO,Near-Earth asteroid orbits which cross the Ear...,a (semi-major axis) > 1.0 AU; q (perihelion) <...,521.846310
1998,2448628,2448628,448628 (2010 VF1),VF1,448628,https://ssd.jpl.nasa.gov/tools/sbdb_lookup.htm...,20.33,False,"[{'close_approach_date': '1906-12-04', 'close_...",False,http://api.nasa.gov/neo/rest/v1/neo/2448628?ap...,228.325794,510.551996,44,2024-11-08 05:27:31,2010-11-02,2024-11-08,5120,128,0,0.230029,4.868,2461000.5,0.653088,1.244139,22.153350,216.330160,506.876265,0.431607,334.338971,2.056671,2.461200e+06,218.571227,0.710233,J2000,APO,Near-Earth asteroid orbits which cross the Ear...,a (semi-major axis) > 1.0 AU; q (perihelion) <...,369.438895
1999,2448721,2448721,448721 (2011 BN24),BN24,448721,https://ssd.jpl.nasa.gov/tools/sbdb_lookup.htm...,20.97,True,"[{'close_approach_date': '1900-04-13', 'close_...",False,http://api.nasa.gov/neo/rest/v1/neo/2448721?ap...,170.041519,380.224396,34,2025-11-21 05:33:11,2011-01-28,2015-10-19,1725,80,0,0.015651,4.360,2461000.5,0.412329,1.544265,3.934717,195.734594,700.940851,0.907520,61.864792,2.181011,2.460662e+06,173.691748,0.513595,J2000,APO,Near-Earth asteroid orbits which cross the Ear...,a (semi-major axis) > 1.0 AU; q (perihelion) <...,275.132958

**Criando tabela de Asteroides Perigosos**

In [37]:
#Filtrando pelo potencial de perigo e depois eliminando essa coluna
df_perigo = df[df['potentially_hazardous'] == True]
df_perigo = df_perigo.drop('potentially_hazardous', axis=1)

#Filtrando pelos maiores diâmetros e exportando
df_perigo = df_perigo.sort_values(['diameter_medium', 'min_orbit_intersection'], ascending=False).reset_index(drop=True)
df_perigo.to_csv('../data/dangest_asteroids.csv', index=False, sep=',')
display(df_perigo)

,id,neo_id,name,short_name,designation,nasa_url,magnitude,close_approach_data,sentry,api_url,diameter_min_m,diameter_max_m,orbit_id,orbit_determination_date,first_observation_date,last_observation_date,data_arc_days,observations_used,orbit_uncertainty,min_orbit_intersection,jupiter_tisserand,epoch,eccentricity,semi_major_axis,inclination,ascending_node_longitude,orbital_period,perihelion_distance,perihelion_argument,aphelion_distance,perihelion_time,mean_anomaly,mean_motion,equinox,orbit_class_type,orbit_class_desc,orbit_class_range,diameter_medium
0,2003122,2003122,3122 Florence (1981 ET3),Florence,3122,https://ssd.jpl.nasa.gov/tools/sbdb_lookup.htm...,14.08,"[{'close_approach_date': '1930-08-29', 'close_...",False,http://api.nasa.gov/neo/rest/v1/neo/2003122?ap...,4060.270583,9079.041030,1013,2026-04-20 06:20:49,1979-03-09,2026-04-19,17208,10093,0,0.043571,3.920,2461000.5,0.423238,1.768878,22.142770,336.040369,859.300632,1.020221,27.884741,2.517535,2.460599e+06,168.257524,0.418945,J2000,AMO,Near-Earth asteroid orbits similar to that of ...,1.017 AU < q (perihelion) < 1.3 AU,6569.655806
1,2004183,2004183,4183 Cuno (1959 LM),Cuno,4183,https://ssd.jpl.nasa.gov/tools/sbdb_lookup.htm...,14.18,"[{'close_approach_date': '1903-09-16', 'close_...",False,http://api.nasa.gov/neo/rest/v1/neo/2004183?ap...,3877.528304,8670.416872,804,2026-04-10 06:55:01,1959-06-05,2026-03-11,24386,5133,0,0.028370,3.572,2461000.5,0.636197,1.980935,6.669481,294.347588,1018.365511,0.720670,237.015910,3.241200,2.461121e+06,317.374038,0.353508,J2000,APO,Near-Earth asteroid orbits which cross the Ear...,a (semi-major axis) > 1.0 AU; q (perihelion) <...,6273.972588
2,2016960,2016960,16960 (1998 QS52),QS52,16960,https://ssd.jpl.nasa.gov/tools/sbdb_lookup.htm...,14.32,"[{'close_approach_date': '1902-10-08', 'close_...",False,http://api.nasa.gov/neo/rest/v1/neo/2016960?ap...,3635.423218,8129.053443,522,2025-12-09 05:26:28,1983-06-14,2025-09-24,15443,3495,0,0.018358,3.000,2461000.5,0.859072,2.200438,17.518135,260.148560,1192.235773,0.310104,243.254521,4.090772,2.460770e+06,69.454754,0.301954,J2000,APO,Near-Earth asteroid orbits which cross the Ear...,a (semi-major axis) > 1.0 AU; q (perihelion) <...,5882.238331
3,2003200,2003200,3200 Phaethon (1983 TB),Phaethon,3200,https://ssd.jpl.nasa.gov/tools/sbdb_lookup.htm...,14.38,"[{'close_approach_date': '1924-10-21', 'close_...",False,http://api.nasa.gov/neo/rest/v1/neo/2003200?ap...,3536.347843,7907.514169,1001,2026-04-10 06:55:02,1983-10-27,2026-03-03,15468,8543,0,0.018701,4.510,2461000.5,0.889718,1.271395,22.312637,265.095572,523.623674,0.140211,322.306512,2.402579,2.460762e+06,163.975097,0.687517,J2000,APO,Near-Earth asteroid orbits which cross the Ear...,a (semi-major axis) > 1.0 AU; q (perihelion) <...,5721.931006
4,2242450,2242450,242450 (2004 QY2),QY2,242450,https://ssd.jpl.nasa.gov/tools/sbdb_lookup.htm...,14.64,"[{'close_approach_date': '1906-07-22', 'close_...",False,http://api.nasa.gov/neo/rest/v1/neo/2242450?ap...,3137.292250,7015.198735,294,2025-06-10 06:17:50,2004-08-20,2025-06-08,7597,3745,0,0.047899,5.441,2461000.5,0.477121,1.083864,37.033205,295.271951,412.155282,0.566730,104.985566,1.600999,2.461156e+06,224.107992,0.873457,J2000,APO,Near-Earth asteroid orbits which cross the Ear...,a (semi-major axis) > 1.0 AU; q (perihelion) <...,5076.245492
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
528,2326290,2326290,326290 Akhenaten (1998 HE3),Akhenaten,326290,https://ssd.jpl.nasa.gov/tools/sbdb_lookup.htm...,21.83,"[{'close_approach_date': '1900-05-10', 'close_...",False,http://api.nasa.gov/neo/rest/v1/neo/2326290?ap...,114.433973,255.882143,73,2026-04-20 06:21:37,1993-04-13,2026-04-20,12060,371,0,0.003509,6.656,2461000.5,0.440139,0.879067,3.377983,53.400593,301.044858,0.492156,309.392559,1.265978,2.460947e+06,63.581510,1.195835,J2000,ATE,Near-Earth asteroid orbits similar to that of ...,a (semi-major axis) < 1.0 AU; q (perihelion) >...,185.158058
529,2414990,2414990,414990 (2011 EM51),EM51,414990,https://ssd.jpl.nasa.gov/tools/sbdb_lookup.htm...,21.90,"[{'close_approach_date': '1900-05-16', 'close_...",False,http://api.nasa.gov/neo/rest/v1/neo/2414990?ap...,110.803882,247.765013,71,2021-04-14 13:07:02,2011-03-10,2020-10-11,3503,272,0,0.013064,4.887,2461000.5,0.335210,1.321475,1.864702,134.146856,554.864662,0.878504,142.286413,1.764447,2.461270e+06,185.008411,0.648807,J2000,APO,Near-Earth asteroid orbits which cross the Ear...,a (semi-major axis) > 1.0 AU; q (perihelion) <...,179.284447
530,2365424,2365424,365424 (2010 KX7),KX7,365424,https://ssd.jpl.nasa.gov/tools/sbdb_lookup.htm...,21.91,"[{'close_approach_date': '1944-05-15', 'close_...",False,http://api.nasa.gov/neo/rest/v1/neo/2365424?ap...,110.294785,246.626636,29,2023-03-01 06:26:36,2010-05-15,2013-05-22,1103,95,1,0.031111,6.059,2461000.5,0.170936,0.989341,21.493703,46.453742,359.432807,0.820228,61.941804,1.158455,2.460988e+06,12.528388,1.001578,J2000,ATE,Near-Earth asteroid orbits similar to that of ...,a (semi-major axis) < 1.0 AU; q (perihelion) >...,178.460710
531,2308635,2308635,308635 (2005 YU55),YU55,308635,https://ssd.jpl.nasa.gov/tools/sbdb_lookup.htm...,21.91,"[{'close_approach_date': '1927-04-09', 'close_...",False,http://api.nasa.gov/neo/rest/v1/neo/2308635?ap...,110.294785,246.626636,137,2025-11-17 05:45:11,2005-12-24,2022-01-06,5857,4013,0,0.000476,5.349,2461000.5,0.430484,1.156862,0.339827,35.922561,454.486092,0.658851,273.570236,1.654872,2.460816e+06,146.193797,0.792103,J2000,APO,Near-Earth asteroid orbits which cross the Ear...,a (semi-major axis) > 1.0 AU; q (perihelion) <...,178.460710
532,2154019,2154019,154019 (2002 CZ9),CZ9,154019,https://ssd.jpl.nasa.gov/tools/sbdb_lookup.htm...,22.07,"[{'close_approach_date': '1912-02-11', 'close_...",False,http://api.nasa.gov/neo/rest/v1/neo/2154019?ap...,102.460147,229.107855,13,2021-04-13 19:34:00,2002-01-10,2005-07-02,1269,69,1,0.025342,4.864,2461000.5,0.360154,1.325269,4.971479,142.840317,557.255603,0.847969,80.880157,1.802569,2.460748e+06,162.932261,0.646023,J2000,APO,Near-Earth asteroid orbits which cross the Ear...,a (semi-major axis) > 1.0 AU; q (perihelion) <...,165.784001

**Fazendo gráfico dos 10 asteroides mais perigosos**

In [38]:
import plotly.express as px
top10 = df_perigo.iloc[0:10]
fig = px.bar(top10, x='diameter_medium', y='short_name', orientation='h', title='10 Asteroides Mais Perigosos', color='diameter_medium', labels={'short_name': 'Nome', 'diameter_medium': 'Diâmetro Médio'}, height=800)
fig.show()
fig.write_image('../graphic/10_Asteroids_Dangerous.png', height=800, width=1920)

Quantidade de observações ao longo do tempo

In [39]:
#Nova coluna com apenas o ano da primeira observação
df['observation_year'] = df['first_observation_date'].dt.year
#Cotando as observações por ano
df_observation = df.groupby('observation_year')['id'].count().reset_index()
#Renomeando coluna
df_observation = df_observation.rename(columns={'id': 'amount'})
df_observation.to_csv('../data/observation_year.csv')
df_observation

    observation_year  amount
0               1893       1
1               1911       1
2               1918       1
3               1924       1
4               1929       1
..               ...     ...
64              2010      30
65              2011      17
66              2012       9
67              2013       6
68              2022       1

[69 rows x 2 columns]

In [40]:
fig_observation = px.line(df_observation, x='observation_year', y='amount', title='Observações De Asteroides Por Ano', labels={'observation_year': 'Ano', 'amount': 'Quantidade'})
fig_observation.show()
fig_observation.write_image('../graphic/Observation_Asteroids_perYear.jpg', height=800, width=1920)

**Média de diâmetro e magnitude por potencial de perigo**

In [41]:
df_asteroids_year = df.groupby('potentially_hazardous').agg(diameter_medium=('diameter_max_m', 'mean'), magnitude_medium=('magnitude', 'mean')).reset_index()
df_asteroids_year[['diameter_medium', 'magnitude_medium']] = df_asteroids_year[['diameter_medium', 'magnitude_medium']].round(2)
df_asteroids_year

   potentially_hazardous  diameter_medium  magnitude_medium
0                  False          1944.22             18.09
1                   True          1372.95             18.78